name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [published, created]
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build Package
        run: |
          python3 -m pip install --upgrade pip build
          python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1